spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: vlad.stavrov2004.stavrov@gmail.com
    password: qwzt bpzy gijq aogv
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true