spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
          - id: auth-server-no-filter
            uri: lb://authorization-service
            predicates:
              - Path=/identity/**

      #  - id: auth-server-registration
      #    uri: lb://authorization-service
      #    predicates:
      #      - Path=/identity/registration
      #    filters:
      #      - name: AuthenticationFilter
      #        args:
      #          requiredRole: ROLE_ADMIN