springdoc:
  swagger-ui:
    configUrl: "/swagger-config.json"
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:


          #- id: main-server-no-filter2
          #  uri: lb://main-service
          #  predicates:
          #    - Path=/chating/chat-socket/**
          #  filters:
          #   - RewritePath=/chating/chat-socket/(?<segment>.*), /$\\{segment}



          - id: company
            uri: lb://main-service
            predicates:
              - Path=/api/companies/**
              - Method=PUT,POST,DELETE
            filters:
              - name: AuthenticationFilter
                args:
                  requiredRole: ROLE_COMPANY

          - id: profile
            uri: lb://main-service

            predicates:
              - Path=/api/profiles/**,/api/workexperiences/**
              - Method=PUT,POST,DELETE
            filters:
              - name: AuthenticationFilter
                args:
                  requiredRole: ROLE_USER

          - id: main-server-no-filter
            uri: lb://main-service
            predicates:
              - Path=/api/identity/**,/api/nodes/**,/api/companies/name/**,/api/vacancies/**,/chating/**, /api/profiles/**,/api/workexperiences/**

          - id: main-server
            uri: lb://main-service
            predicates:
              - Path=/api/**
            filters:
              - name: AuthenticationFilter

          #- id: auth-server-registration
          #  uri: lb://authorization-service
          #  predicates:
          #    - Path=/api/identity/registration
          #  filters:
          #    - name: AuthenticationFilter
          #      args:
          #        requiredRole: ROLE_ADMIN
logging:
  level:
    org.springframework.cloud.gateway: TRACE